name: Run rspec workflow

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        gemfile: [Gemfile]
        ruby-version: ['3.0']
    runs-on: ubuntu-latest
    container:
      image: ruby:3.0.0

    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - name: Setup gems
        run: gem install --system 
      - name: Run Bundle Install
        run: bundle install
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs bundle install and caches installed gems automatically
          bundler: ${{ env.BUNDLER_VERSION || 'default' }}
          rubygems: ${{ env.RUBYGEMS_VERSION || 'latest' }}
      - run: bundle exec rake
