#some stuff because github doesn't like empty folders/files?
name: Run Rspec Tests

on:
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:10.11
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - name: Cache Ruby
      uses: actions/cache@preview
      id: cache
      with:
        path: ~/local/rubies
        key: ruby-2.7.0

    - name: Set up Ruby 2.7.0
      uses: clupprich/ruby-build-action@master
      id: ruby
      with:
        ruby-version: 2.7.0
        cache-available: ${{ steps.cache.outputs.cache-hit == 'true' }}

    - name: Print ruby version
      run: ${{ steps.ruby.outputs.ruby-path }} --version


    - name: Build and test with rspec
      run: |
        gem install bundler -v 1.17.3
        bundle install --jobs 4 --retry 3
        bundle exec rspec spec